# Generated by Django 4.2.5 on 2023-10-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDataFileModel',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('gridfs_id', models.CharField(blank=True, max_length=30)),
                ('file_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='VarietyPaperModel',
            fields=[
                ('paper_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variety', models.CharField(choices=[('BUCKSY200', 'Buck SY 200'), ('LENOX', 'Lenox'), ('ACA360', 'ACA 360'), ('ALGARROBBO', 'Algarrobo'), ('ARSLAK', 'Arslak'), ('BAGUETTE601', 'Baguette 601'), ('BASILIO', 'Basilio'), ('BG620', 'Bg 620'), ('BG750', 'Bg 750'), ('BIOINTA2004', 'Biointa 2004'), ('BIOINTA3005', 'Biointa 3005'), ('BIOINTA3006', 'Biointa 3006'), ('CEDRO', 'Cedro'), ('FLORIPAND', 'Floripan 200'), ('GUAYABO', 'Guayabo'), ('MSINTA119', 'MS INTA 119'), ('ÑANDUBAY', 'Ñandubay'), ('SURSEM2330', 'Sursem 2330')], max_length=50, verbose_name='Variedad')),
                ('humidity_percentage', models.FloatField(verbose_name='Humedad')),
                ('performance', models.IntegerField(verbose_name='Redimiento (kg/ha)')),
                ('relative_performance', models.IntegerField(verbose_name='Redimiento Relativo')),
                ('grains_count', models.IntegerField(verbose_name='Numero de granos')),
                ('grains_per_spike', models.IntegerField(verbose_name='Granos por espiga')),
                ('weight_per_thousand_grains', models.FloatField(verbose_name='Peso por mil granos')),
                ('proteins_percentage', models.FloatField(verbose_name='Proteinas')),
                ('ph', models.FloatField(verbose_name='Potencial de Hidrogeno')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDataModel',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_reference', models.CharField(choices=[('RED INTA 2022', 'Red INTA 2022'), ('INTA LABOULAYE', 'INTA Laboulaye')], max_length=50, verbose_name='Referencia')),
                ('paper_type', models.CharField(choices=[('VARIEDADES', 'Variedades')], max_length=20, verbose_name='Tipo de ensayo')),
                ('year', models.DateField(verbose_name='Año')),
                ('location', models.CharField(choices=[('ADELIA MARIA', 'Adelia Maria'), ('BELL VILLE', 'Bell Ville'), ('JUSTINIANO POSSE', 'Justiniano Posse'), ('LA CARLOTA', 'La Carlota'), ('LABOULAYE', 'Laboulaye'), ('MARCOZ JUAREZ', 'Marcos Juarez'), ('ONAGOITY', 'Onagoity')], max_length=50, verbose_name='Localidad')),
                ('latitude', models.IntegerField(null=True, verbose_name='Latitud')),
                ('longitude', models.IntegerField(null=True, verbose_name='Longitud')),
                ('paper_pepetition', models.IntegerField(default=1, verbose_name='Repeiciones del ensayo')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.varietypapermodel', verbose_name='Ensayo')),
            ],
        ),
    ]
