# Generated by Django 4.2.5 on 2023-09-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TecDataExcelFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
