# Generated by Django 4.2.5 on 2023-10-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_paper_technicaldatamodel_paper_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varietypapermodel',
            name='variety',
            field=models.CharField(choices=[('BUCKSY200', 'Buck SY 200'), ('LENOX', 'Lenox'), ('ACA360', 'ACA 360'), ('ACA365', 'ACA 365'), ('ALGARROBBO', 'Algarrobo'), ('ARSLAK', 'Arslak'), ('BAGUETTE601', 'Baguette 601'), ('BASILIO', 'Basilio'), ('BG620', 'Bg 620'), ('BG750', 'Bg 750'), ('BIOINTA2004', 'Biointa 2004'), ('BIOINTA3005', 'Biointa 3005'), ('BIOINTA3006', 'Biointa 3006'), ('CEDRO', 'Cedro'), ('FLORIPAND', 'Floripan 200'), ('GUAYABO', 'Guayabo'), ('MSINTA119', 'MS INTA 119'), ('ÑANDUBAY', 'Ñandubay'), ('SURSEM2330', 'Sursem 2330')], max_length=50, verbose_name='Variedad'),
        ),
    ]
