# Generated by Django 4.2.5 on 2023-12-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_varietypapermodel_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPaperModel',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_reference', models.CharField(choices=[('RED INTA 2022', 'Red INTA 2022'), ('INTA LABOULAYE', 'INTA Laboulaye')], max_length=50, verbose_name='Referencia')),
                ('paper_type', models.CharField(choices=[('VARIEDADES', 'Variedades')], max_length=20, verbose_name='Tipo de ensayo')),
                ('year', models.DateField(verbose_name='Año')),
                ('location', models.CharField(choices=[('ADELIA MARIA', 'Adelia Maria'), ('BELL VILLE', 'Bell Ville'), ('JUSTINIANO POSSE', 'Justiniano Posse'), ('LA CARLOTA', 'La Carlota'), ('LABOULAYE', 'Laboulaye'), ('MARCOZ JUAREZ', 'Marcos Juarez'), ('ONAGOITY', 'Onagoity')], default='SELECCIONAR', max_length=50, verbose_name='Localidad')),
                ('latitude', models.IntegerField(null=True, verbose_name='Latitud')),
                ('longitude', models.IntegerField(null=True, verbose_name='Longitud')),
                ('paper_pepetition', models.IntegerField(default=1, verbose_name='Repeiciones del ensayo')),
            ],
            options={
                'db_table_comment': 'Papers de campañas',
            },
        ),
        migrations.RenameModel(
            old_name='TechnicalDataFileModel',
            new_name='CampaignPaperFileModel',
        ),
        migrations.AlterField(
            model_name='varietypapermodel',
            name='variety',
            field=models.CharField(choices=[('BUCKSY200', 'Buck SY 200'), ('LENOX', 'Lenox'), ('ACA360', 'ACA 360'), ('ACA365', 'ACA 365'), ('ALGARROBO', 'Algarrobo'), ('ARSLAK', 'Arslak'), ('BAGUETTE601', 'Baguette 601'), ('BASILIO', 'Basilio'), ('BG620', 'Bg 620'), ('BG750', 'Bg 750'), ('BIOINTA2004', 'Biointa 2004'), ('BIOINTA3005', 'Biointa 3005'), ('BIOINTA3006', 'Biointa 3006'), ('CEDRO', 'Cedro'), ('FLORIPAND', 'Floripan 200'), ('GUAYABO', 'Guayabo'), ('MSINTA119', 'MS INTA 119'), ('ÑANDUBAY', 'Ñandubay'), ('SURSEM2330', 'Sursem 2330')], max_length=50, verbose_name='Variedad'),
        ),
        migrations.DeleteModel(
            name='TechnicalDataModel',
        ),
        migrations.AddField(
            model_name='campaignpapermodel',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.varietypapermodel', verbose_name='Ensayo'),
        ),
    ]
