# Generated by Django 4.2.5 on 2023-12-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaignpapermodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignpapermodel',
            old_name='paper',
            new_name='paper_variety',
        ),
    ]
